<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Ramphor\\Slug\\Remover\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ramphor\\Slug\\Remover\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2::$classMap;

        }, null, ClassLoader::class);
    }
}
