<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'bdf78aadedcdffbd9264705d73f17eca' => $vendorDir . '/jankx/helpers/loader.php',
);
