<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2
{
    public static $files = array (
        'bdf78aadedcdffbd9264705d73f17eca' => __DIR__ . '/..' . '/jankx/helpers/loader.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Ramphor\\Slug\\Manager\\' => 21,
        ),
        'J' => 
        array (
            'Jankx\\Helpers\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ramphor\\Slug\\Manager\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Jankx\\Helpers\\' => 
        array (
            0 => __DIR__ . '/..' . '/jankx/helpers/src/Helpers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita46f9641ddc96c236c39c0c1aeb4d2d2::$classMap;

        }, null, ClassLoader::class);
    }
}
